In [ ]:
# ------
#  Pandas using in Python 
# 
# 
# ------

In [2]:
import pandas as pd
pd.__version__

u'0.23.4'

### Pandas中的一纬数组:Series

In [7]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [8]:
data.values # 返回numpy 中的 结构

array([0.25, 0.5 , 0.75, 1.  ])

In [9]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [15]:
data[1]/data[0]

2.0

In [19]:
data.values[0:3]

array([0.25, 0.5 , 0.75])

In [23]:
data.index[0:3]

RangeIndex(start=0, stop=3, step=1)

In [28]:
 for i in range(0,3):
        print data.index[0:3][i]

0
1
2


###  Series 和Numpy 中的一维向量之间的核心区别是:Index 

In [36]:
data_with_index = pd.Series([0.0 0.25, 0.50, 0.75, 1.0],
                index = ['a','b','c','d','e'])
data_with_index

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [42]:
data_with_index['d']

0.75

In [46]:
data_with_index.index[2]

'c'

In [50]:
data_with_index.values[2]

0.5

### 字典与Series

由于index 的存在，Series 可以看成是一个字典

In [4]:
population_dict = {'California':28232,
                  'Texas':28382,
                  'New York':90283,
                  'Florida': 89283,
                  'Illiosn':29322}
population  = pd.Series(population_dict)

population

California    28232
Florida       89283
Illiosn       29322
New York      90283
Texas         28382
dtype: int64

### 注意排序

In [61]:
population.index  # 注意排序

Index([u'California', u'Florida', u'Illiosn', u'New York', u'Texas'], dtype='object')

In [62]:
population.index[2]

'Illiosn'

In [63]:
population.values

array([28232, 89283, 29322, 90283, 28382], dtype=int64)

In [66]:
population[population.index[1]] # population.index[1] = u'Florida

89283

In [65]:
population.index[1]

'Florida'

In [67]:
population

California    28232
Florida       89283
Illiosn       29322
New York      90283
Texas         28382
dtype: int64

In [68]:
population['California']

28232

In [69]:
population['California':'Illiosn']

California    28232
Florida       89283
Illiosn       29322
dtype: int64

In [70]:
population['Illiosn':'Texas']

Illiosn     29322
New York    90283
Texas       28382
dtype: int64

### 创建Series

In [72]:
pd.Series([2.,3.3,'d'])

0      2
1    3.3
2      d
dtype: object

In [75]:
pd.Series(5,index = [100,200,909,2292])

100     5
200     5
909     5
2292    5
dtype: int64

In [6]:
data_1 = pd.Series({'1':'one', 1:'s'})
data_1

1      s
1    one
dtype: object

In [87]:
data_1.index

Index([1, u'1'], dtype='object')

In [86]:
data_1.index[0]

1

In [8]:
data_1[data_1.index[0]]

's'

In [90]:
type(data_1.index[1]) # data_1.index[1] = str

str

In [96]:
pd.Series( {2:'Two',3:'three',1:'Theone'}, index = [2,3,4,5] )

2      Two
3    three
4      NaN
5      NaN
dtype: object

### Pandas 中的DataFrame

In [126]:
population_dict = {'Beijing':0x108929,
                  'ShangHai':0x208292,
                  'TianJin':0x222292,
                  'ShanDong':0x562631 }
population = pd.Series(population_dict
                      )

In [127]:
population

Beijing     1083689
ShanDong    5645873
ShangHai    2130578
TianJin     2237074
dtype: int64

In [128]:
area_dict = {'Beijing': 423967, 
             'ShangHai': 695662, 
             'TianJin': 141297,
             'ShanDong': 170312
             }
area = pd.Series(area_dict)

In [129]:
area

Beijing     423967
ShanDong    170312
ShangHai    695662
TianJin     141297
dtype: int64

In [130]:
infor = pd.DataFrame({'population':population,
                      'area':area})
# show infor
infor

area  population
Beijing   423967     1083689
ShanDong  170312     5645873
ShangHai  695662     2130578
TianJin   141297     2237074

In [132]:
infor.index

Index([u'Beijing', u'ShanDong', u'ShangHai', u'TianJin'], dtype='object')

In [140]:
infor.index[0]

'Beijing'

In [143]:
infor['area']

Beijing     423967
ShanDong    170312
ShangHai    695662
TianJin     141297
Name: area, dtype: int64

In [144]:
infor['population']

Beijing     1083689
ShanDong    5645873
ShangHai    2130578
TianJin     2237074
Name: population, dtype: int64

In [156]:
infor[0:2]

area  population
Beijing   423967     1083689
ShanDong  170312     5645873

In [157]:
infor[0:2]['area']

Beijing     423967
ShanDong    170312
Name: area, dtype: int64

### 注意!!! 在DataFrame中。使用[]是获取一列的数据

In [158]:
infor['area']  

Beijing     423967
ShanDong    170312
ShangHai    695662
TianJin     141297
Name: area, dtype: int64

In [159]:
infor

area  population
Beijing   423967     1083689
ShanDong  170312     5645873
ShangHai  695662     2130578
TianJin   141297     2237074

### 创建DataFrame

通过单一Series 

In [163]:
pd.DataFrame(population, columns = ['population'])

population
Beijing      1083689
ShanDong     5645873
ShangHai     2130578
TianJin      2237074

In [168]:
### 通过多个字典比较 - 每个字典可以理解成是在描述一个样本
data = [{'a':i,'b':2*i} for i in range(5)]
data = pd.DataFrame(data)
data

a  b
0  0  0
1  1  2
2  2  4
3  3  6
4  4  8

In [176]:
dict_1 = {'a':1, 'b':2, 'c':3,'d':4}
dict_2 = {'AA':11, 'BC':22, 'CC':33,'DD':44} 

In [177]:
pd.DataFrame([dict_1,dict_2])

AA    BC    CC    DD    a    b    c    d
0   NaN   NaN   NaN   NaN  1.0  2.0  3.0  4.0
1  11.0  22.0  33.0  44.0  NaN  NaN  NaN  NaN

## 通过Numpy二维数组

In [180]:
import numpy as np
pd.DataFrame(np.random.rand(3,2),
            columns = ['foo','bar'],
            index = ['a','b','c'])

foo       bar
a  0.371355  0.786119
b  0.317158  0.482665
c  0.228184  0.098359

### 通过Numpy中structured array 

In [186]:
A = np.zeros(3,dtype = [('A','i8'),('B','f8')])

In [187]:
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [188]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

### Index 

In [195]:
ind = pd.Index([2,5,7,9,11])

In [196]:
ind  # 
print "ind is one Immutable Array"

ind is one Immutable Array


In [197]:
ind 

Int64Index([2, 5, 7, 9, 11], dtype='int64')

In [198]:
ind[0:2]

Int64Index([2, 5], dtype='int64')

In [199]:
ind[::2]

Int64Index([2, 7, 11], dtype='int64')

In [200]:
ind.size

5

In [201]:
ind

Int64Index([2, 5, 7, 9, 11], dtype='int64')

In [202]:
ind.ndim

1

In [203]:
ind.dtype

dtype('int64')

In [204]:
ind

Int64Index([2, 5, 7, 9, 11], dtype='int64')

In [205]:
ind.shape

(5L,)

In [206]:
ind.ndim

1

In [207]:
ind.dtype

dtype('int64')

In [208]:
ind 

Int64Index([2, 5, 7, 9, 11], dtype='int64')

In [209]:
ind[0]

2

In [212]:
indA = pd.Index([1,3,5,7,9,11])
indB = pd.Index([2,3,5,7,19,11])

In [213]:
indA

Int64Index([1, 3, 5, 7, 9, 11], dtype='int64')

In [214]:
indB

Int64Index([2, 3, 5, 7, 19, 11], dtype='int64')

### 取交集

In [215]:
indA&indB 

Int64Index([3, 5, 7, 11], dtype='int64')

### 取并集

In [217]:
indA|indB

Int64Index([1, 2, 3, 5, 7, 9, 11, 19], dtype='int64')

In [218]:
indA^indB

Int64Index([1, 2, 9, 19], dtype='int64')