### Concat and Append 

### 回归:Numpy 中的concatenate 矩阵连接

In [23]:
import numpy as np
x = [1,2,3]
y = [4,5,6]
z = [7,8,9]
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 数字拼接 - concatenate

In [24]:
x = [ [1,2],[3,4] ]
np.concatenate([x,x], axis = 1)  # axis = 1 表示列方向摆放堆积

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [25]:
np.concatenate([x,x], axis = 0)  # axis = 0 表示按照行方向来摆放堆积

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

### Pandas 的数据连接

In [30]:
import pandas as pd 
ser1 = pd.Series(['A','B','C'],index = [1,2,3])
ser2 = pd.Series(['D','E','F'],index = [4,5,6])
pd.concat([ser1,ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [28]:
ser1

1    A
2    B
3    C
dtype: object

In [37]:
pd.DataFrame(np.random.randint(0,16,(3,5)),columns = range(5),index = range(3))

0   1   2   3   4
0  3   6  15  15  15
1  4  15   0   4  13
2  0   6  15   2   1

In [51]:
def make_data(cdata,digitaldata):
    dict_ = {c:[str(c) + str(digital) for digital in digitaldata] for c in cdata }
    return pd.DataFrame(dict_,digitaldata)

make_data('HEXLOWORLD',range(0,10))

D   E   H   L   O   R   W   X
0  D0  E0  H0  L0  O0  R0  W0  X0
1  D1  E1  H1  L1  O1  R1  W1  X1
2  D2  E2  H2  L2  O2  R2  W2  X2
3  D3  E3  H3  L3  O3  R3  W3  X3
4  D4  E4  H4  L4  O4  R4  W4  X4
5  D5  E5  H5  L5  O5  R5  W5  X5
6  D6  E6  H6  L6  O6  R6  W6  X6
7  D7  E7  H7  L7  O7  R7  W7  X7
8  D8  E8  H8  L8  O8  R8  W8  X8
9  D9  E9  H9  L9  O9  R9  W9  X9

In [55]:
a = str('A') + str('9')

In [56]:
df = make_data('Thisistheone',range(0,len('Thisistheone')))

In [57]:
df

T    e    h    i    n    o    s    t
0    T0   e0   h0   i0   n0   o0   s0   t0
1    T1   e1   h1   i1   n1   o1   s1   t1
2    T2   e2   h2   i2   n2   o2   s2   t2
3    T3   e3   h3   i3   n3   o3   s3   t3
4    T4   e4   h4   i4   n4   o4   s4   t4
5    T5   e5   h5   i5   n5   o5   s5   t5
6    T6   e6   h6   i6   n6   o6   s6   t6
7    T7   e7   h7   i7   n7   o7   s7   t7
8    T8   e8   h8   i8   n8   o8   s8   t8
9    T9   e9   h9   i9   n9   o9   s9   t9
10  T10  e10  h10  i10  n10  o10  s10  t10
11  T11  e11  h11  i11  n11  o11  s11  t11

In [66]:
df1 = make_data('Bp',[1,2])
df1

B   p
1  B1  p1
2  B2  p2

In [67]:
df2 = make_data('Bp',[2092,20])
df2

B      p
2092  B2092  p2092
20      B20    p20

In [69]:
pd.concat([df1,df2])

B      p
1        B1     p1
2        B2     p2
2092  B2092  p2092
20      B20    p20

### 处理相同索引

In [72]:
df_x = make_data('AN',[0,2])
df_x

A   N
0  A0  N0
2  A2  N2

In [74]:
df_y = make_data('AN',[0,2])
df_y

A   N
0  A0  N0
2  A2  N2

In [86]:
pd.concat([df_x,df_y])

A   N
0  A0  N0
2  A2  N2
0  A0  N0
2  A2  N2

In [82]:
try:
    pd.concat([df_x,df_y],verify_integrity=True)
except ValueError as e:
    print "error"

error


### 忽略相同索引

In [85]:
pd.concat([df_x,df_y],ignore_index = True)

A   N
0  A0  N0
1  A2  N2
2  A0  N0
3  A2  N2

### 制作多层索引

In [93]:
df3 = pd.concat([df_x,df_y],keys = ['X','Y'])
df3

A   N
X 0  A0  N0
  2  A2  N2
Y 0  A0  N0
  2  A2  N2

### Join 

In [95]:
df4 = make_data('DCS',[1,2,3])
df4

C   D   S
1  C1  D1  S1
2  C2  D2  S2
3  C3  D3  S3

In [97]:
df5 = make_data('ADC',[5,6,7])
df5

A   C   D
5  A5  C5  D5
6  A6  C6  D6
7  A7  C7  D7

In [101]:
pd.concat([df4,df5])

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A   C   D    S
1  NaN  C1  D1   S1
2  NaN  C2  D2   S2
3  NaN  C3  D3   S3
5   A5  C5  D5  NaN
6   A6  C6  D6  NaN
7   A7  C7  D7  NaN

### join = 'inner '仅仅是重合的部分显示出来

In [102]:
pd.concat([df4,df5],join = 'inner')  

C   D
1  C1  D1
2  C2  D2
3  C3  D3
5  C5  D5
6  C6  D6
7  C7  D7

In [104]:
pd.concat([df4,df5],join = 'outer')  

c:\python27\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


A   C   D    S
1  NaN  C1  D1   S1
2  NaN  C2  D2   S2
3  NaN  C3  D3   S3
5   A5  C5  D5  NaN
6   A6  C6  D6  NaN
7   A7  C7  D7  NaN

### 使用join_axes 

In [109]:
pd.concat([df4,df5],join_axes = [df4.columns]) # join_axes  = ['C','D','S']

C   D    S
1  C1  D1   S1
2  C2  D2   S2
3  C3  D3   S3
5  C5  D5  NaN
6  C6  D6  NaN
7  C7  D7  NaN

In [108]:
df4.columns

Index([u'C', u'D', u'S'], dtype='object')

### append() - 跟Python 中的list -append 方法不同的是，pandas 中的append 并内有修改原来的数据

In [113]:
df4.append(df5)## = pd.concat([df4,df5])

A   C   D    S
1  NaN  C1  D1   S1
2  NaN  C2  D2   S2
3  NaN  C3  D3   S3
5   A5  C5  D5  NaN
6   A6  C6  D6  NaN
7   A7  C7  D7  NaN

In [114]:
df4

C   D   S
1  C1  D1  S1
2  C2  D2  S2
3  C3  D3  S3

In [115]:
df5

A   C   D
5  A5  C5  D5
6  A6  C6  D6
7  A7  C7  D7